### ISSUE TITLE
Support node target with webpack

### ISSUE THREAD

**Issue by AndersDJohnson** [kentcdodds/kcd-scripts#19]
Sometimes I like to pipe my Node programs through Webpack, mainly so I have an isomorphic and consistent build tooling setup, including watching scripts, using Babel even on some node_modules, use custom loaders, minify/obfuscate code, etc. We could support that here: https://github.com/kentcdodds/kcd-scripts/blob/63caff0/src/config/babelrc.js#L12-L14

**Comment by kentcdodds** [comment]
Hey @AndersDJohnson! Thanks for the issue! I don't currently have plans to bundle with webpack, but you could probably just use the `--bundle` flag which will make it bundle with rollup. If you don't like the rollup config you can make your own.

I don't think that I want to add this to `kcd-scripts` because I think it's out of scope. Thanks!
