### ISSUE TITLE
Add `package-lock.json` or `yarn.lock`

### ISSUE THREAD

**Issue by AndersDJohnson** [kentcdodds/kcd-scripts#22]
We should lock down dependencies. Not sure if you prefer `yarn` or `npm >=5`.

**Comment by kentcdodds** [comment]
I prefer `npm >= 5`, but I don't like lock files in my open source projects. [I explicitly ignore them](https://github.com/kentcdodds/kcd-scripts/blob/e9b1d5fa1a774e9d2f0d200ff8ffa4565edc69df/.gitignore#L9-L12) because I find they cause more harm than good in my open source projects.

Thanks though!
