### ISSUE TITLE
Cannot use with nps or other script runners

### ISSUE THREAD

**Issue by AndersDJohnson** [kentcdodds/kcd-scripts#23]
The `ifScript` logic sprinkled throughout does not understand scripts defined outside of `package.json`, e.g., via [`nps`](https://www.npmjs.com/package/nps).

**Comment by kentcdodds** [comment]
Thanks @AndersDJohnson. This is true. That said, I don't want to worry about supporting that directly. Instead you can simply do this:

```javascript
{
  "scripts": {
    "start": "nps",
    "build": "nps build",
    "lint": "nps lint"
  }
}
```

I realize that slightly defeats the purpose of nps, but I think it'll keep this project more simple and straightforward. Also, projects where I'm using kcd-scripts don't use nps because I only need a handful of scripts so it doesn't fall into the problem space that nps was intended to solve.

Thanks though!
