### ISSUE TITLE
Fix resolveBin for windows

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/kcd-scripts#8]
`resolveBin`: https://github.com/kentcdodds/kcd-scripts/blob/bd3d6425598db7f25ee15f14238739abf5b28178/src/utils.js#L21-L44

It's responsible for taking a module name (like `eslint`) and getting a path to the executable binary. If the path to the executable is the same as the one that's in the `$PATH` environment variable (using `which`), then we can return the raw binary name itself and execute a script with that, otherwise we'll return the full path so it's executed with the full path (because it's not available in `$PATH` presumably.

This is useful because if the user sees the script we run (which they do in some situations) then the script will be shorter.

It works on linux systems right now, but apparently the result of `which.sync` is to a file ending in `.CMD` and isn't a symlink (so the `realpathSync` doesn't resolve it to the binary path).

So we need to find a package that will do this for us (I already tried [`resolve-bin`](https://www.npmjs.com/package/resolve-bin) and it didn't work the way I want it to) or fix this function up to make it work for windows as well as linux.

Anyone wanna help out?

**Comment by rossipedia** [comment]
Ok I'm not sure I understand what the problem is. The executable for Windows _is_ the `*.cmd` file, which is a thin wrapper around invoking node.exe with `pkg.bin`.

For example, the contents of `node_modules\.bin\webpack.cmd` is:

```cmd
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\webpack\bin\webpack.js" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\webpack\bin\webpack.js" %*
)
```
and likewise, the contents of `which.cmd` is:
```cmd
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\which\bin\which" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\which\bin\which" %*
)
```
As you can see, they follow the same general format, the only thing differing is the path to the `*.js` file that node will execute.

This is required because in Windows, executable files are determined by file extension rather than a permissions bit as they are in *nix land.

The `*.cmd` file can be treated as the executable, and can be started via `child_process.exec` or `child_process.spawn` and it _should_ just do the right thing.

**Comment by rossipedia** [comment]
Ok, I see what the issue is (I cloned the repo and ran the test suite). You might have to rethink the tests here, since the way Windows handles command lines / dir separators / executables is so different from *nix. Gotta run to the store, but I might take a crack at it later tonight.

**Comment by kentcdodds** [comment]
Thanks for looking into it! If you have another suggestion let me know! I'm thinking that with the serializers I add we can normalize the paths so it's not an issue for tests, but I definitely want it to work the same as far as the implementation goes. I'd really love it to not have the full path to the executable if the executable exists in the PATH by its name already.

**Comment by alexandernanberg** [comment]
I might be missing something, but why not use `npx` to run the scripts instead? From what I've seen that should remove the need for the `resolveBin` util altogether.

**Comment by kentcdodds** [comment]
Hmmm... Interesting thought. That might work! Would you like to give it a try?

**Comment by alexandernanberg** [comment]
Sure, I'll give it a go!

**Comment by adamdharrington** [comment]
nice one @kentcdodds !
